### PR TITLE
Remove the binder link from example notebooks that cannot be run there 

### PR DESCRIPTION
**Pull request by pingelit**
As the title says. 
This PR adapts the `nbsphinx_prolog` to remove the binder link badge from the example page and replace it with a note to download the notebook.

Furthermore, this PR move the IR measurement notebook to the `no_binder` folder.
This is done because that notebook cannot be run in binder.

### CODE REVIEW

**Comment by f-brinkmann** [comment]
Thanks this looks good to me. But I just noticed that NBViewer also does not work for the measurement notebook - neither here, nor on main. Should we remove the link as well and only leave the download link?

**Review by ahms5 — APPROVED** [review]

**Comment by pingelit** [comment]
I noticed the nbviewer link as well. But as far as I can tell, the link is not in "our" prologue. Should I investigate this in this PR?

**Review by f-brinkmann — APPROVED** [review]

**Comment by f-brinkmann** [comment]
In that case, lets maybe better open a seprate issue

**Comment by mberz** [comment]
> I noticed the nbviewer link as well. But as far as I can tell, the link is not in "our" prologue. Should I investigate this in this PR?

It's right below the changes you made.

```
      <script>
        if (document.location.host) {
          let nbviewer_link = document.createElement('a');
          nbviewer_link.setAttribute('href',
            'https://nbviewer.org/url' +
            (window.location.protocol == 'https:' ? 's/' : '/') +
            window.location.host +
            window.location.pathname.slice(0, -4) +
            'ipynb');
          nbviewer_link.innerHTML = 'Or view it on <em>nbviewer</em>';
          nbviewer_link.classList.add('reference');
          nbviewer_link.classList.add('external');
          document.currentScript.replaceWith(nbviewer_link, '.');
        }
      </script>

```

Albeit, it's most probably a different issue with this particular notebook. As mentioned above, nbconvert does not execute the notebooks. Let's make this a separate issue/PR.

**Review by mberz — APPROVED** [review]

**Pull request merged**
