### PR TITLE
Remove duplicate include of gallery

### PR DESCRIPTION
**Pull request by sikersten**
The gallery is included on the first page, leading to an error in the tests, because corresponding identifiers exist twice.

I removed the include from the first page and instead added a card. Open for suggestions on the text and the name of the button on the card.

### CODE REVIEW

**Comment by sikersten** [comment]
Should we name it "Example gallery" or "Examples gallery"? Would need to be updated in the navigation toolbar accordingly.

**Comment by ahms5** [comment]
Or just Examples?
its sorter and contains all information.

**Comment by hoyer-a** [comment]
We could work around that problem by inserting a nb gallery into 'index.rst' and just including the links to the notebooks using 'start-after' and 'end-before'.

**Comment by sikersten** [comment]
closed by #42

**Pull request closed without merging**
